# -*- coding: utf-8 -*-
"""Lab1_N01484167.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1grN3nTmxJmPQr-5XbGiIVnP79W_TdnKW
"""

#Lab 1
#N01484167
#Jared Henry
#Version 1/25/2023


#global variables
numWindows = 0
numDoors = 0
roomHeight = 0
roomWidth = 0
roomLength = 0
userHeight = 0
userWeight = 0
userInput = 1



def paintRoom(length, width, height, num_of_doors, num_of_windows):
  totalLength = length * 2
  totalWidth = width * 2
  paintCov = 315
  deductPaint = (num_of_doors * 25) + (num_of_windows * 10)
  totalArea = (totalLength * height) + (totalWidth * height)
  totalPaint = (totalArea - deductPaint ) / paintCov
  return totalPaint

def userBMI (userHeight, userWeight):

  bmiCalc = (userWeight * 703)/ (userHeight * userHeight)

  return bmiCalc

while userInput == 1 or userInput == 2:
  
  print("Welcome to Python Program.")
  print("Menu Options are:")
  print("\tEnter 1 for calculating gallons of paint needed to paint a room")
  print("\tEnter 2 for the calculating Body Mass Index")
  print("\tEnter any other value to quit the program")
  userInput = int(input())
 #paint caluclator prompts
  if userInput == 1:
    print("-------------------------------------------")
    print("Welcome to the paint calculator!")
    print("Enter the length of the room:") 
    roomLength = float(input())
    print("Enter the width of the room:")
    roomWidth = (float(input()))
    print("Enter the height of the room:")
    roomHeight = float(input())
    print("How many doors are in the room?")
    numDoors = float(input())
    print("How many windows are in the room?")
    numWindows = float(input())

    print('%.2f' % paintRoom(roomLength, roomWidth, roomHeight, numDoors, numWindows) + " gallons of paint are needed to paint a room "  + '%.2f' % roomWidth + " feet wide by "
    + '%.2f' % roomLength + " feet long by " + '%.2f' % roomHeight + " feet high with " + '%.0f' % numDoors + " doors and " + '%.0f' % numWindows
    + " windows.")

  if userInput == 2:
    print("Welcome to the body mass index (BMI) calculator.")
    print("Enter your weight in pounds: ")
    userWeight = float(input())
    print("Enter your height in inches: ")
    userHeight = float(input())
    print("Your BMI is " + '%.2f' % userBMI(userHeight, userWeight) + 
          ". According to NIH, you are")
    if userBMI(userHeight, userWeight) < 18.5:
      print("Underweight.")
    if userBMI(userHeight, userWeight) > 18.5 and userBMI(userHeight, userWeight) < 24.9:
      print("Normal.")
    if userBMI(userHeight, userWeight) > 25 and userBMI(userHeight, userWeight) < 29.9 :
      print("Overweight.")
    if userBMI(userHeight, userWeight) > 30:
       print("Obese.")

    
   
else: 
  #credit card payment calculator
  def paymentCalc(totalDue):
    
      paymentDue = totalDue * .021
      if paymentDue >=10:
        return paymentDue
      else:
        if totalDue > 10:
          return 10
        else:
          return totalDue

  print("Welcome to the credit card payment calculator!")
  print("Please enter the total balance of the credit card: ")
  totalDue = float(input())
  print("The minimum payment due on your credit card payment is: $" + '%.2f' % paymentCalc(totalDue))

  #character counting
  print("Welcome to the Character Counter Program:")
  
  
  userString = input()
  userString = userString.lower() 
  userString = userString.replace(" ","")
  
  counter = 0
  myDic = {}
  for keys in userString:
    myDic[keys] = myDic.get(keys,0) +1
    if myDic[keys] <=1:
      counter = counter +1
print("Total number of characters including special characters: ")
print(counter)
for items in myDic.items():
     print(items)
     

#String Calculation Program

counter = 0;

print("Please enter a list of user names: ")
userNames = str(input())
userNames = userNames.upper() 
userNames = userNames.split(" ")

counter = 0
nameDic = {}
maxLeng = 0

def stringCalc(userNames):
  counter = 0
  maxLeng = 0
  jNames = []
  print("Original List ->")
  print(userNames) 
  for items in userNames:
   nameDic[items] = nameDic.get(items,0) + 1
   if len(items) >= 5:
    counter += 1
   if maxLeng < len(items):
    maxLeng = len(items)
    longestString = items
   if items[0] == "J" and len(items) <= 5:
     
     jNames.append(items)
  
  
  print("Longest String ->" + str(longestString))
  print("Total strings values greater than 5: ") 
  print(int(counter))
  print("Names that start with the letter J and have five characters or less: "  + str(jNames))
    
stringCalc(userNames)