# -*- coding: utf-8 -*-
"""lab3_creditcard_soln

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1SNX1nArPfGX3P3U1pBLHpCwSnSGLBy
"""

import random


class CreditCard:
#constructor
  def __init__(self, cardnum, userName, exDate):
    self.cardnum = cardnum
    self.userName = userName
    self.exDate = exDate
    self.creditLimit = 1000
    self.cardBalance = random.randint(0, 999)
    self.cardType = {1: 'Visa', 2: 'Master', 3: 'Amex', 4: 'Discover'}
#getters and setters  
  def set_cardOwner(self, userName):
    self.userName = userName
  
  def get_cardOwner(self):
    return self.userName
  
  def get_cardType(self):
    if int(self.cardnum[5]) not in self.cardType:
     return 'Not Supported Card Type'
    if int(self.cardnum[5]) in self.cardType:
      return self.cardType
    
     
    
#returns false when invalid card type or card balance is exceeded
#returns true when card balance is successfuly processed
  def processOrder(self, amount):
    if self.cardBalance < amount or int(self.cardnum[5]) not in self.cardType:
      return False
    self.cardBalance -= amount
    return True
#used to print a string of card number, peroname, and exDate when specifically called
#returns a card num, userName, or exDate per project requirements.
  def __str__(self):
    return 'Credit Card Number: {}, Person name: {}, Expiry Date: {}'.format(self.cardnum, self.userName, self.exDate)