# -*- coding: utf-8 -*-
"""Lab4_N01484167

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wmT0XTcGfRz1b3P--6qCsW0NO66dQDje
"""

#Lab 4
#N01484167 - Jared Henry

import numpy as np
import pandas as pd

df = pd.read_csv('brfss-cdc.csv')

#genfromtxt reads in numeric data
arr = np.genfromtxt("./brfss-cdc.csv", delimiter=",",dtype = np.int64,skip_header = 1)
print("First Five Rows of the Data:")
print(arr[:5]) #returns first 5 indexes of arr
print(arr.shape)

# Calculate weight change information into list
weight_change = []
for index in arr:
    weight_change.append(index[2] - index[3]) #returns product of current weight and weight 1 year ago

weight_change = np.array(weight_change)

# Append weight_change array to the main data array
arr = np.append(arr, np.reshape(weight_change, (-1, 1)), axis=1)

print("\nFirst Five Rows of the Data with Weight Changes:")
print(arr[:5])
print("Shape of the data: ", arr.shape)
print("\n")
#split out first five rows by gender = male
arr2 = [] #males
arr3 = [] #females
j = 0
for val in arr: # loops through arr and appends males and females into emptry array 2 and 3 based on the gender
    if(val[5] == 1):
      arr2.append(val)
    else:
      arr3.append(val)
arr2 = np.array(arr2) #converts array 2 into a np array
arr3 = np.array(arr3) #converts array 3 into a np array

#Male data point calculations
mean1 = np.mean(arr2) #average for males
median1 = np.median(arr2) #median for males
stdDev1 = np.std(arr2) #standard deviation for males
q75, q25 = np.percentile(arr2, [75 ,25])#interquartile percentage caluclations
# Interquaritle range (IQR)takes in two quarter params and equates the interquartile solution
IQR1 = q75 - q25

#Female data point calculations
mean2 = np.mean(arr3) #average for females
median2 = np.median(arr3) #median for females
stdDev2 = np.std(arr3) #standard deviation for females
q75, q25 = np.percentile(arr3, [75 ,25])#interquartile percentage caluclations
# Interquaritle range (IQR)takes in two quarter params and equates the interquartile solution
IQR2 = q75 - q25

#Male data points
print("Descriptive Statistics for Data relevant to Males: ")
print("Mean: ", "%.2f" % mean1)
print("Median: ", median1)
print("Standard Deviation: ","%.2f" % stdDev1)
print("Interquartile Range: ", IQR1)

#print for first 5 data indexes for male
print("\nFirst Five Rows of the Data relevant to Males: ")
for index in range(5): #loops through and prints first five data elements for males
  print(arr2[index])
print("Shape of the data:", arr2.shape) #prints shape of the data for males
print("\n")

#Females data points
print("Descriptive Statistics for Data relevant to Females: ")
print("Mean: ","%.2f" % mean2)
print("Median: ", median2)
print("Standard Deviation: ","%.2f" % stdDev2)
print("Interquartile Range: ", IQR2)

#print for first 5 data indexes for female
print("\nFirst Five Rows of the Data relevant to Females:")
for index in range(5): #loops through and prints first five data elements for females
    print(arr3[index])
print("Shape of the data:", arr3.shape) #prints shape of the data for females